import {
  faSnowflake,
  faDoorOpen,
  faBuilding,
  faElevator,
  faCar,
  faSeedling,
  faFire,
  faCouch,
  faTemperatureQuarter,
  faWifi,
  faParking,
  faHouseSignal,
  faShieldAlt,
  faBox,
  faSwimmer,
  faWheelchair,
} from '@fortawesome/free-solid-svg-icons';

export const amenitiesIcons = {
  'air conditioning': faSnowflake,
  balcony: faDoorOpen,
  basement: faBuilding,
  elevator: faElevator,
  garage: faCar,
  garden: faSeedling,
  fireplace: faFire,
  furnished: faCouch,
  heating: faTemperatureQuarter,
  internet: faWifi,
  parking: faParking,
  'smart home features': faHouseSignal,
  'security system': faShieldAlt,
  'storage room': faBox,
  'swimming pool': faSwimmer,
  'wheelchair accessible': faWheelchair,
};
